---
title: Identifying the best predictive biomarker in pharmacogenomics through multiple comparisons with the best
output:
  html_document: default
  mainfont: Times New Roman
  fontsize: 12
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

## LOAD PACKAGES AND FUNCTIONS

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(data.table)
library(glmnet)
library(gridExtra)
```

```{r}
dir <- "~/PROJECT/Dissertation/Code/" # CHANGE IT TO YOUR OWN PATH

source(paste0(dir,"Functions/Functions-IT_p1.R"))
source(paste0(dir,"Functions/Functions-IT_p2.R"))
source(paste0(dir,"Functions/Functions-Ranking.R"))
source(paste0(dir,"Functions/Functions-LSmeans+MCB.R"))
source(paste0(dir,"Functions/Functions-Fig.R"))
```

## LOAD THE GENOTYPE DATA

```{r}
load(paste0(dir,"Data/geno.Rdata"))
```

## SET SEED

```{r}
set.seed(100)
```

## FIGURE S1

```{r warning=FALSE}
Gx <- cbind.data.frame("chr19.rs429358.pos45411941"=g1, G[,2301:2304]) %>% as.matrix()
N <- c(seq(50, 300, 50), 400, 500, 1000, 2000, 5000)
nrep <- 1000

est <- matrix(NA, ncol = length(N), nrow = nrep)
for (i in 1:length(N)) {
  n <- N[i]
  for (k in 1:nrep) {
    #set.seed(k)
    index <- sample(1:nrow(Gx), n, replace = T)
    Gxx <- Gx[index,]
    Tr <- rbinom(nrow(Gxx), 1, 0.5)
    est[k,i] <- cor(Gxx[which(Tr==1),])[1,2] - cor(Gxx[which(Tr==0),])[1,2]
  }
}

colnames(est) <- N
```

```{r}
p <- plot.est.ols(est, N)
```

```{r}
dir2 <- "~/PROJECT/Dissertation/Code/Results/" # CHANGE IT TO YOUR OWN PATH

ggsave(filename = paste0(dir2,"FigS1.png"), plot = p,
       device = "png",
       width = 30,
       height = 20,
       units = "cm",
       dpi = 300,
       limitsize = FALSE)
```






