---
title: Identifying the best predictive biomarker in pharmacogenomics through multiple comparisons with the best
output:
  html_document: default
  mainfont: Times New Roman
  fontsize: 12
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

## LOAD PACKAGES AND FUNCTIONS

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(data.table)
library(glmnet)
library(gridExtra)
```

```{r}
dir <- "~/PROJECT/Dissertation/Code/" # CHANGE IT TO YOUR OWN PATH

source(paste0(dir,"Functions/Functions-IT_p1.R"))
source(paste0(dir,"Functions/Functions-IT_p2.R"))
source(paste0(dir,"Functions/Functions-Ranking.R"))
source(paste0(dir,"Functions/Functions-LSmeans+MCB.R"))
source(paste0(dir,"Functions/Functions-Fig.R"))
```

## LOAD THE GENOTYPE DATA

```{r}
load(paste0(dir,"Data/geno.Rdata"))
```

## SET SEED

```{r}
set.seed(22231)
```

## FIGURE S4 

```{r}
Tr <- rbinom(nrow(G), 1, 0.5)

Gx <- cbind.data.frame("chr19.rs429358.pos45411941"=g1, "chr19.rs7412.pos45412079"=g2, G[,2301:2308]) %>% as.matrix()

gamma = 1
alpha = 0
beta = 0
sigma = 1

nrep = 500
```

```{r}
sample1 <- sample2 <- sample3 <- sample4 <- double()

for (i in 1:nrep) {
  if(i %% 10 == 0){print(paste0("replicate = ", i))}
  
  Y <- gamma*Tr + alpha*g1 + beta*(Tr*g1) + rnorm(nrow(Gx), 0, sigma)
  
  re1 <- LSmeans_MCB_est(Y, Tr, Gx)
  re2 <- pvalue.rank(Y, Tr, Gx)
  re3 <- Lasso(Y, Tr, Gx)
  re4 <- IT(Y, Tr, Gx)
  
  sample1[i] <- which.max(re1)
  sample2[i] <- which.max(re2)
  if(mean(re3 == 0) != 1){sample3[i] <- which.max(re3)}
  if(mean(re3 == 0) == 1){sample3[i] <- sample(1:10,1)}
  sample4[i] <- which.max(re4)
}

sample1 <- sample1 %>% sort()
sample2 <- sample2 %>% sort()
sample3 <- sample3 %>% sort()
sample4 <- sample4 %>% sort()

theory0 <- rep(1:10,each=nrep/10)

select.seq <- cbind.data.frame(sample1, sample2, sample3, sample4, theory0)
colnames(select.seq) <- c("3M","P-value Ranking","Lasso","IT","Uniform")
```

```{r warning=FALSE}
p <- plot.QQ(select.seq)
```

```{r}
dir2 <- "~/PROJECT/Dissertation/Code/Results/" # CHANGE IT TO YOUR OWN PATH

ggsave(filename = paste0(dir2,"FigS4.png"), plot = p,
       device = "png",
       width = 30,
       height = 30,
       units = "cm",
       dpi = 300,
       limitsize = FALSE)
```





